server:
  port: 8985
  
spring:
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: movie-api
  sql:
    init:
      platform: h2
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
