insert into movie (title) values ('Yankee Zulu');
insert into movie (title) values ('Chris Rock: Bring the Pain');
insert into movie (title) values ('Thunderbolt and Lightfoot');
insert into movie (title) values ('Phffft');
insert into movie (title) values ('Onion Field, The');
insert into movie (title) values ('Place Beyond the Pines, The');
insert into movie (title) values ('House at the End of the Street');
insert into movie (title) values ('Cape Fear');
insert into movie (title) values ('Buddy Buddy');
insert into movie (title) values ('One Deadly Summer (L''été meurtrier)');
insert into movie (title) values ('35 and Ticking');
insert into movie (title) values ('Opening Night');
insert into movie (title) values ('Mambo Italiano');
insert into movie (title) values ('Jimmy and Judy');
insert into movie (title) values ('Side Street');
insert into movie (title) values ('Dinosaur Project, The');
insert into movie (title) values ('Samurai Fiction (SF: Episode One)');
insert into movie (title) values ('Year of the Gun');
insert into movie (title) values ('American Gun');
insert into movie (title) values ('Landscape Suicide');
insert into movie (title) values ('Dead Calm');
insert into movie (title) values ('Cookout, The');
insert into movie (title) values ('Chinese Zodiac (Armour of God III) (CZ12)');
insert into movie (title) values ('Together (Han ni Zai Yiki)');
insert into movie (title) values ('Middle of Nowhere');
insert into movie (title) values ('Full Moon High');
insert into movie (title) values ('Love Happy');
insert into movie (title) values ('Bury My Heart at Wounded Knee');
insert into movie (title) values ('Goalie''s Anxiety at the Penalty Kick, The (Die Angst des Tormanns beim Elfmeter)');
insert into movie (title) values ('Ideal Husband, An');
insert into movie (title) values ('The Missing');
insert into movie (title) values ('Endeavour');
insert into movie (title) values ('Foreign Correspondent');
insert into movie (title) values ('Barney''s Version');
insert into movie (title) values ('Last Kiss, The (Ultimo bacio, L'')');
insert into movie (title) values ('Waiter (Ober)');
insert into movie (title) values ('Pirates of Silicon Valley');
insert into movie (title) values ('Buddy Boy');
insert into movie (title) values ('Ransom (a.k.a. The Terrorists)');
insert into movie (title) values ('Barricade');
insert into movie (title) values ('8:46');
insert into movie (title) values ('Summer Holiday');
insert into movie (title) values ('Paths of Glory');
insert into movie (title) values ('Amityville Horror, The');
insert into movie (title) values ('A.K.');
insert into movie (title) values ('Godsend');
insert into movie (title) values ('Virunga');
insert into movie (title) values ('Fear of a Black Hat');
insert into movie (title) values ('Bill Cunningham New York');
insert into movie (title) values ('Break-in');
insert into movie (title) values ('Crazy Stranger, The (Gadjo Dilo)');
insert into movie (title) values ('Death Sentence');
insert into movie (title) values ('Libeled Lady');
insert into movie (title) values ('Kill Bill: Vol. 1');
insert into movie (title) values ('All Dogs Go to Heaven 2');
insert into movie (title) values ('Prime');
insert into movie (title) values ('Guide for the Married Man, A');
insert into movie (title) values ('RiP: A Remix Manifesto');
insert into movie (title) values ('Gitarrmongot');
insert into movie (title) values ('The Matrix');
insert into movie (title) values ('True Confessions');
insert into movie (title) values ('Breezy');
insert into movie (title) values ('Night of the Lepus');
insert into movie (title) values ('Chato''s Land');
insert into movie (title) values ('Staten Island');
insert into movie (title) values ('Last Remake of Beau Geste, The');
insert into movie (title) values ('D.L. Hughley: Reset');
insert into movie (title) values ('Stealing Beauty');
insert into movie (title) values ('If I Were You');
insert into movie (title) values ('Sweet Evil (L''enfance du mal)');
insert into movie (title) values ('Pajama Party');
insert into movie (title) values ('Passed Away');
insert into movie (title) values ('Paul Blart: Mall Cop');
insert into movie (title) values ('My Way');
insert into movie (title) values ('Wadd: The Life & Times of John C. Holmes');
insert into movie (title) values ('God Said ''Ha!''');
insert into movie (title) values ('Reeker');
insert into movie (title) values ('Hurry Sundown');
insert into movie (title) values ('Missing Picture, The (L''image manquante)');
insert into movie (title) values ('1984');
insert into movie (title) values ('Suicide Club (Jisatsu saakuru)');
insert into movie (title) values ('Dancing in the Rain (Ples v dezju)');
insert into movie (title) values ('Hey Bartender');
insert into movie (title) values ('Free Willy 2: The Adventure Home');
insert into movie (title) values ('Take Me Out to the Ball Game');
insert into movie (title) values ('Under the Same Moon (Misma luna, La)');
insert into movie (title) values ('Man with an Apartment (Czlowiek z M-3)');
insert into movie (title) values ('Life Partners');
insert into movie (title) values ('Breaking News (Daai si gin)');
insert into movie (title) values ('Cradle Will Rock');
insert into movie (title) values ('To Paint or Make Love (Peindre ou faire l''amour)');
insert into movie (title) values ('Kismet');
insert into movie (title) values ('Love at Large');
insert into movie (title) values ('Klansman, The');
insert into movie (title) values ('Sonic Outlaws');
insert into movie (title) values ('Lucky You');
insert into movie (title) values ('Endgame');
insert into movie (title) values ('Fire');
insert into movie (title) values ('Plague Dogs, The');