spring:
  application:
    name: rabbit-subscriber-2
  rabbitmq:
    host: localhost
    port: 5672

queues:
  oak: pallet-town
  fanout: pokeCenter2
  
exchanges:
  fanout: pokeMart
  
server:
  port: 8458
