spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zulmak
    username: root
    password: root
    
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 4631
  
logging:
  level:
    '[com.skillstorm]': info
    root: info
  
#turn on the actuaor endpoints
#strongly recommended not to enable all of them
management:
  endpoints:
    web:
      exposure:
        include: "*"

#We'll come back to this  
skillstorm:
  classroom:
    champion:
      name: Miles
      times: 9001
    fav-trainer: Miles
    first-loser: Taylor
    mascot: Husky
